# Generated by Django 4.2.1 on 2023-06-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phonk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonk_singer',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
